<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="truber_p1">

	<xacro:property name="width" value="0.40" />
	<xacro:property name="bodylen" value="0.60" />
	<xacro:property name="height" value="0.1" />

	<xacro:property name="wheel_radius" value="0.06"/>
	<xacro:property name="wheel_width" value="0.04"/>
	
	<xacro:property name="wheel_base" value="0.35"/>
	<xacro:property name="rear_wheel_seperation" value = "0.3"/>

	<xacro:property name="max_steer_angle" value="0.6"/>
	<xacro:property name="max_steer_vel" value="1.0"/>
	

	<link name="base_link">
		<visual>
		    <geometry>
		        <box size="${bodylen} ${width} ${height}"/>
		    </geometry>
		    <origin xyz="0.175 0 ${height/2}" rpy="0 0 0"/>
		</visual>
		<collision>
		    <geometry>
				<box size="${bodylen} ${width} ${height}"/>
			</geometry>
			<origin xyz="0.175 0 ${height/2}" rpy="0 0 0"/>
		</collision>	
	</link>
	
	<joint name="front_steer_joint" type="revolute">
		<parent link="base_link"/>
		<child link="front_wheel_steer"/>
		<axis xyz="0 0 1"/>
		<limit effort="1000" lower="${-max_steer_angle}" upper="${max_steer_angle}" velocity="${max_steer_vel}"/>
		<origin rpy="0 0 0" xyz="${wheel_base} 0 0"/>
	</joint>
	
	<link name="front_wheel_steer">
		<visual>
			<geometry>
				<cylinder length="${wheel_radius}" radius="0.05"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 ${-wheel_radius/2}"/>
		</visual>
	</link>
	
	<joint name="front_wheel_joint" type="continuous">
		<parent link="front_wheel_steer"/>
		<child link="front_wheel"/>
		<axis xyz="0 1 0"/>
		<origin rpy="0 0 0" xyz="0 0 ${-wheel_radius}"/>
	</joint>
	
	<link name="front_wheel">
		<visual>
			<geometry>
				<cylinder length="${wheel_width}" radius="${wheel_radius}"/>
			</geometry>
			<origin xyz="0 0 0" rpy="1.57075 1.57075 0"/>
		</visual>
	</link>
	
	<joint name="rear_left_joint" type="continuous">
		<parent link="base_link"/>
		<child link="rear_left_wheel"/>
		<axis xyz="0 1 0"/>
		<origin rpy="0 0 0" xyz="0 ${-0.5*rear_wheel_seperation} ${-wheel_radius}"/>
	</joint>
	
	<link name="rear_left_wheel">
		<visual>
			<geometry>
				<cylinder length="${wheel_width}" radius="${wheel_radius}"/>
			</geometry>
			<origin xyz="0 0 0" rpy="1.57075 1.57075 0"/>
		</visual>
	</link>
	
	<joint name="rear_right_joint" type="continuous">
		<parent link="base_link"/>
		<child link="rear_right_wheel"/>
		<axis xyz="0 1 0"/>
		<origin rpy="0 0 0" xyz="0 ${0.5*rear_wheel_seperation} ${-wheel_radius}"/>
	</joint>
	
	<link name="rear_right_wheel">
		<visual>
			<geometry>
				<cylinder length="${wheel_width}" radius="${wheel_radius}"/>
			</geometry>
			<origin xyz="0 0 0" rpy="1.57075 1.57075 0"/>
		</visual>
	</link>
	
	


</robot>
